# Generated by Django 4.1.3 on 2022-12-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_club', '0002_director_movie_review_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(max_length=7),
        ),
    ]
